### ISSUE TITLE
[Feature request] Add and remove to/from world group command

### ISSUE THREAD

**Issue by bobhenl** [Zrips/TradeMeAddon#36]
Hi, I'm using player worlds plugin https://www.spigotmc.org/resources/%E2%AD%90-playerworldspro-%E2%AD%90-nether-and-the-end-support-async-loading-expiration-1-8-1-16-3.72113/ and if you add way to add world group, it would be useful for me when the new world will be created, due to players have it's own nether and end. Same for removing, when the world will be removed, for ex. when it's expire, then I wanna automatically remove world from the world group list.

Talking about this:
```
# World groups to separate trades if you have multiverse or similar plugin
WorldGroups:
  Group1:
  - World
  - World_nether
  - World_the_end
  Group2:
  - ''
  Group3:
  - ''
  Group4:
  - ''
  Group5:
  - ''
```
